#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

termite -e calcurse &
bspc node -d 'todo'

bspc monitor HDMI-1 -d main prog web irc mail todo htop
bspc monitor DVI-I-1 -d doc doc2 ncmpcpp

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off


# bspc rule -a brave                       desktop='^3' focus=on follow=on

