[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'
xcape -e 'Super_L=F12'

setxkbmap -option "grp:alt_shift_toggle,grp_led:scroll" -layout "us, ca" &
#grp:switch, <- pour right alt thing!!

feh --bg-tile ~/pictures/wallpapers/black.jpeg

~/dotfiles/scripts/screens.sh

picom -b --config ~/dotfiles/picom/picom.conf
xset -dpms;xset s off

exec i3
