[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'

setxkbmap -option "grp:switch,grp:alt_shift_toggle,grp_led:scroll" -layout "us, ca" &

#feh --bg-scale ~/pictures/wallpapers/darksouls.jpeg

~/dotfiles/scripts/screens.sh

exec bspwm
