#!/usr/bin/env python
import subprocess

themes = ["3024", "apathy", "ashes", "atelier-cave", "atelier-cave-light", "atelier-dune", "atelier-dune-light", "atelier-estuary", "atelier-estuary-light", "atelier-forest", "atelier-forest-light", "atelier-heath", "atelier-heath-light", "atelier-lakeside", "atelier-lakeside-light", "atelier-plateau", "atelier-plateau-light", "atelier-savanna", "atelier-savanna-light", "atelier-seaside", "atelier-seaside-light", "atelier-sulphurpool", "atelier-sulphurpool-light", "atlas", "bespin", "black-metal", "black-metal-bathory", "black-metal-burzum", "black-metal-dark-funeral", "black-metal-gorgoroth", "black-metal-immortal", "black-metal-khold", "black-metal-marduk", "black-metal-mayhem", "black-metal-nile", "black-metal-venom", "brewer", "bright", "brogrammer", "brushtrees", "brushtrees-dark", "chalk", "circus", "classic-dark", "classic-light", "codeschool", "cupcake", "cupertino", "darktooth", "default-dark", "default-light", "dracula", "eighties", "embers", "flat", "fruit-soda", "github", "google-dark", "google-light", "grayscale-dark", "grayscale-light", "greenscreen", "gruvbox-dark-hard", "gruvbox-dark-medium", "gruvbox-dark-pale", "gruvbox-dark-soft", "gruvbox-light'hard", "gruvbox-light-medium", "gruvbox-light-soft", "harmonic-dark", "harmonic-light", "heetch", "heetch-light", "helios", "hopscotch", "horizon-dark", "ia-dark", "ia-light", "icy", "irblack", "isotope", "macintosh", "marrakesh", "materia", "material-darker", "material-lighter", "material-palenight", "material-vivid", "mellow-purple", "mexico-light", "mocha", "monokai", "nord", "ocean", "oceanicnext", "onedark", "one-light", "outrun-dark", "papercolor-dark", "papercolor-light", "paraiso", "phd", "pico", "pop", "porple", "railscasts", "rebecca", "seti", "shapeshifter", "snazzy", "solarflare", "solarized-dark", "solarized-light", "spacemacs", "summerfruit-dark", "summerfruit-light", "synth-midnight-dark", "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tube", "twilight", "unikitty-dark", "unikitty-light", "woodland", "xcode-dusk", "zenburn"]


for theme in themes:    
    cmd = "curl https://raw.githubusercontent.com/chriskempson/base16-xresources/master/xresources/base16-%s.Xresources >> ~/dotfiles/x/themes/%s" % (theme, theme)

    subprocess.Popen(cmd, shell=True)
